### ISSUE TITLE
Failed to load Info.plist

### ISSUE THREAD

**Issue by elad823** [bugfender/rn-bugfender#1]
I am getting this error after building the project:

Failed to load Info.plist from bundle at path .../CoreSimulator/Devices/B9A32448-39BA-4CCF-A777-99AD9FA83FED/data/Library/Caches/com.apple.mobile.installd.staging/temp.35Ua1g/extracted/MyApp/Frameworks/BugfenderSDK.framework

**Comment by jgimenez** [comment]
Hi @elad823 , this usually happens when you integrate the library as an embedded framework, but `BugfenderSDK.framework` is a static framework. I would recommend removing it and adding it again, following strictly the installation instructions from README.
