### ISSUE TITLE
Trouble installing Bugfender on 0.63.2

### ISSUE THREAD

**Issue by mickejointsjohansson** [bugfender/rn-bugfender#14]
Hi!
We're having trouble installing Bugfender on React Native 0.63.2.

We are using cocoapods since before.

What we do is
- yarn add @bugfender/rn-bugfender
- (cd ios && pod install) 

After this building the iOS app using 
- npx react-native run-ios
gives us the following error:

error: Multiple commands produce '...Build/Products/Debug-iphonesimulator/cocoapods-artifacts-Debug.txt':
1) That command depends on command in Target 'app' (project 'app'): script phase “[CP] Prepare Artifacts”
2) That command depends on command in Target 'appTests' (project 'app'): script phase “[CP] Prepare Artifacts”

It seems we can get rid of the problem by removing the generated "Prepare Artifacts"-step under our appTests target (leaving it in the app target). But running pod install after this will add the "Prepare Artifacts"-step again. We're thinking it might be added by the automatic linking?

Any ideas on what to do?

**Comment by jgimenez** [comment]
Hi @mickejointsjohansson , it would be great to have full logs in order to analyze this. Also, it looks like it could be a CocoaPods bug. Have you tried updating CocoaPods to the lastest version?

**Comment by mickejointsjohansson** [comment]
Thanks for the quick reply @jgimenez! We think we have solved it by simply removing those extra targets (we weren't really using them) which gets us going again.

**Comment by jgimenez** [comment]
OK great!
