### ISSUE TITLE
Error when logging

### ISSUE THREAD

**Issue by jaltin** [bugfender/rn-bugfender#16]
Hi,

I am trying to add Bugfender in a react native app. I have followed the installation instructions, but I get this error when trying to log with a statement like this:

`Bugfender.i('NISSE-I', message);`

Error I get is:
`TypeError: _rnBugfender.default.i is not a function. (In '_rnBugfender.default.i('NISSE-I', message)', '_rnBugfender.default.i' is undefined)`.

React Native: 0.63.3
Client OS & Version: iOS 14.2, on iPad

Any idea what could be going wrong?

**Comment by jgimenez** [comment]
Hi @jaltin , it looks like you're calling a non-existent function. Bugfender.i() doesn't exist. Maybe you can use Bugfender.d() instead.

You can see all the methods supported in the README file or here:
https://github.com/bugfender/rn-bugfender/blob/master/bugfender.js

**Comment by jaltin** [comment]
> You can see all the methods supported in the README file or here:
> https://github.com/bugfender/rn-bugfender/blob/master/bugfender.js

Thanks for your help @jgimenez. Unfortunately something else came in between so I haven't managed to test it yet, but it sounds absolutely right what you say. I see that you closed the issue which is correct, and if/when I get a chance to test again I will post here.

**Comment by jgimenez** [comment]
Sure, please feel free to follow up if there's anything else we can help you with.

I'm wondering why you were calling `i()`, though. Did you find this code in an example or copy-paste it from somewhere else, maybe?

**Comment by jaltin** [comment]
> I'm wondering why you were calling `i()`, though. Did you find this code in an example or copy-paste it from somewhere else, maybe?

We were trying to replace an existing logging tool with bugfender, and that framework has debug/info/warning/error log levels. We tried to replace one of the existing info logs with a bugfender log, and erroneously/stupidly then used an i() instead of d(). Our bad.

**Comment by jgimenez** [comment]
Ah I see, good to know. We're going to add more logging levels soon. The native Bugfender SDKs already support it, but the RN adapter doesn't yet. Stay tuned, we'll update it soon.
