### ISSUE TITLE
No logs on iOS

### ISSUE THREAD

**Issue by vlad-ps** [bugfender/rn-bugfender#19]
I am not getting any logs on iOS devices. Logging is working fine on Android. 

What I did:
1. `yarn add @bugfender/rn-bugfender`
2. `pod install`
3. Add `Bugfender.init("our_secret_app_key");` to index.js

After these steps I can see logs from Android devices but no logs from iOS. 

Manual steps listed in the library are outdated. New React Native versions have auto linking, and no libraries are being added to Podfile, so your recommended Podfile cannot be used. 

 Also, Bugdfender iOS SDK is on v.1.10.2 and React Native binding repo is still on v1.9. This needs to be updated. 
 
 I'm on React Native v0.64.2, React 17.0.2. My Podfile targets iOS 11.

**Comment by jgimenez** [comment]
Hi there, are you logging something like the installation steps suggest?

    Bugfender.d ("REACT", "This is a debug log in Bugfender from React Native");

**Comment by vlad-ps** [comment]
Hi @jgimenez, no, I don't do that. All I'm doing is adding `Bugfender.init("our_secret_app_key")`; to index.js. After that I am able to see the log below in the Android phone I'm using for testing, while I see nothing from an iPhone. Thanks for your help!

<img width="956" alt="Screen Shot 2021-07-28 at 4 49 10 PM" src="https://user-images.githubusercontent.com/75272184/127394372-5e19006f-0f10-47ec-8f89-b5ad607e459a.png">

**Comment by jgimenez** [comment]
Please check the installation instructions in the README to see how to logs stuff.

This KB article might also help: https://support.bugfender.com/en/articles/1497769-what-types-of-logs-can-bugfender-collect
