### ISSUE TITLE
Unable to find module with Gradle path ':@bugfender/rn-bugfender'

### ISSUE THREAD

**Issue by tamarinda** [bugfender/rn-bugfender#2]
Hi, 

I am getting the issue `Unable to find module with Gradle path ':@bugfender/rn-bugfender'` when compiling for Android.

**Specs**
Android Studio 3.0
react-native 0.51.0
rn-bugfinder 1.0.0

**Possible Reason**
When linking the library, the module name contains `/` like: `@bugfender/rn-bugfender` which seems to be deprecated: [docs](https://docs.gradle.org/4.2/release-notes.html#path-separator-characters-in-names-are-deprecated)

**Solution**
A solution would maybe be to change the name of the library.
Provisionally it is possible to compile it with just a few changes, changing `:@bugfender/rn-bugfender` to `rn-bugfender`

In `settings.gradle`
Replace:
```
include ':@bugfender/rn-bugfender'
project(':@bugfender/rn-bugfender').projectDir = new File(rootProject.projectDir, '../node_modules/@bugfender/rn-bugfender/android')
```
With this:
```
include ':rn-bugfender'
project(':rn-bugfender').projectDir = new File(rootProject.projectDir, '../node_modules/@bugfender/rn-bugfender/android')
```

And under dependencies
Replace:
```
compile project(':@bugfender/rn-bugfender')
```
With this:
```
compile project(':rn-bugfender')
```

**Comment by franmontiel** [comment]
Hi, thanks for your report. I am able to reproduce the issue using the same react-native version (0.51.0)

This is a known react-native issue when using _react-native link_ command for linking the dependencies. 
Fortunately this has been solved form version 0.56. I've tested it on version 0.57.1 and the gererated lines are now correct.

If you keep using version 0.51.0 you can always apply your workraound as it is perfectly valid.
