### ISSUE TITLE
Getting error "Undefined Symbol: _OBJC_CLASS_$_Bugfender" when running build configuration in release mode.

### ISSUE THREAD

**Issue by jimfoambox** [bugfender/rn-bugfender#20]
Hi,

I have recently installed Bugfender via the recommended React Native installation from your repo, and everything was working fine and as expected when I built the app in both iOS and Android, (my iOS working scheme was in a debug build with debug executable checked).

 When I attempt to do a scheme with a release build configuration in Xcode without debug executable, I get a build failure with the error: 

```
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_Bugfender", referenced from:
      objc-class-ref in libRNBugfender.a(RNBugfender.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This happens under the Link ReactMobile(i386) task during the build.

So far none of my research has come up with a way forward: any help, ideas, or strategies to get this operational would be greatly appreciated.  

Thanks for your time.

**Comment by jimfoambox** [comment]
This was resolved when changing "Build Active Architecture Only" in "Release" mode to "Yes" (In Architectures in the project Build Settings).

Needed to ignore the older architectures (i386) that was causing some conflict with the simulator, if I understand it correctly.

**Comment by jgimenez** [comment]
Hi there, Bugfender is not built for i386 architecture. This architecture was deprecated years ago, so it shouldn't be necessary for modern builds.
