### ISSUE TITLE
Error: this class is not key value coding-compliant for the key

### ISSUE THREAD

**Issue by jamieGardyn** [bugfender/rn-bugfender#21]
I have been getting the following error since upgrading xCode several months ago...

Exception '[<__NSDictionaryI 0x60000179a560> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key userId.' was thrown while invoking setDeviceString on target RNBugfender with params (
    userId,
    "c02c10-bc-4699-9e4-e9cb9950"
)

**Comment by jgimenez** [comment]
Hi @jamieGardyn , I'm sorry about that. This is a known issue of the iOS native SDK that is being used by this version of rn-bugfender. We're working on an update that will resolve the issue, I hope you have it soon.

**Comment by jamieGardyn** [comment]
> Hi @franmontiel , thanks for your help!
> 
> I am now getting the following error when running pod install...
> 
> [!] CocoaPods could not find compatible versions for pod "BugfenderSDK": In snapshot (Podfile.lock): BugfenderSDK (= 1.10.1, ~> 1.9)
> 
> In Podfile: RNBugfender (from `../node_modules/@bugfender/rn-bugfender`) was resolved to 1.1.5, which depends on BugfenderSDK (~> 1.10.3)
> 
> Specs satisfying the `BugfenderSDK (= 1.10.1, ~> 1.9), BugfenderSDK (~> 1.10.3)` dependency were found, but they required a higher minimum deployment target.

To answer my own question - I had to cd ios and then run pod update BugfenderSDK

**Comment by jgimenez** [comment]
Hi @jamieGardyn , the core of the error shows here:

> dependency were found, but they required a higher minimum deployment target.

Your application might be supporting an iOS version that BugfenderSDK does not support (we support iOS 10).
