### ISSUE TITLE
feature request - add array of parameters to log functions

### ISSUE THREAD

**Issue by elirangoshen** [bugfender/rn-bugfender#4]
Thanks for making Bugfender work with react native, its really good !

my suggestion is to add the ability to insert array of parameters , to the log funtioins (aka .d or .debug) like console.log, to make it  easier. in console.log, you can add multiple parameters and it would print them all, while in bugfender it looks like it can get exactly 2. its not a big deal, but when you build an app and using  console.log so its more convenient to send the same params to bugfender as well. (so you can actually e.g use 1 function for their both).

**Comment by RubenVot** [comment]
Hi @elirangoshen thanks a lot for taking your time to submit feature requests! 

We have received authorization to investigate the extension of the Bugfender and making its behaviour similar to the console.log 

We will be working on this on the next sprint. Additionally, if you have any other suggestion or code example we also accept PR.  
Closing the issue as I already added to our internal ticketing system.
