### ISSUE TITLE
feature request - install with cocoapods

### ISSUE THREAD

**Issue by leozzitowned** [bugfender/rn-bugfender#5]
Do you have any plans to make this package compatible with Cocoapods? I believe is not a good practice keep huge files (such as BugfenderSDK.framework) inside your source code, it makes your repository bigger than it should be.

Thank you for making such a great tool like Bugfender available for React Native!!!

**Comment by RubenVot** [comment]
I'm glad to say that we have a new cocoapods-compatible version of the SDK in the testing phase right now. 
The release was planned for the last week but there was a bad release of the react-native-cli and the testing team delayed as they couldn't test it properly. 
It should be available very soon.

**Comment by RubenVot** [comment]
@leozzitowned this is now available: https://github.com/bugfender/rn-bugfender/releases/tag/1.1.0 
Give it a try and send us some feedback :)
