### ISSUE TITLE
Please update it to React Native new version

### ISSUE THREAD

**Issue by nnrohu** [bugfender/rn-bugfender#56]
I am unable to update my project because of this library.

Please update it to React Native version 0.70.6

**Comment by jgimenez** [comment]
Hi @nnrohu , we regualary update this library, so we'll push an update soon. If you'd like to contribute, you can open a pull request.

**Comment by doup** [comment]
We've upgraded **@bugfender/rn-bugfender** to RN `0.70.6`. Check the lates version: `2.1.2`.
