### ISSUE TITLE
iOS missing bitcode when archiving the project

### ISSUE THREAD

**Issue by mmaass** [bugfender/rn-bugfender#66]
After the integration of Bugfender via your library this just happened while archiving the project:

`ld: '/Users/.../Library/Developer/Xcode/DerivedData/igp-dalegoduhtiafmchyvwfdwnbnayb/Build/Intermediates.noindex/ArchiveIntermediates/igp/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/BugfenderSDK/BugfenderSDK.framework/BugfenderSDK' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/.../Library/Developer/Xcode/DerivedData/igp-dalegoduhtiafmchyvwfdwnbnayb/Build/Intermediates.noindex/ArchiveIntermediates/igp/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/BugfenderSDK/BugfenderSDK.framework/BugfenderSDK' for architecture arm64`

I wonder if I should just disable bitcode in the build settings as in XCode 14 it will be deprecated anyways. (I'm on 13.2)

> Starting with Xcode 14, bitcode is no longer required for watchOS and tvOS applications, and the App Store no longer accepts bitcode submissions from Xcode 14.
https://developer.apple.com/documentation/Xcode-Release-Notes/xcode-14-release-notes

**Comment by jgimenez** [comment]
Hi there, Bitcode has always been a bit difficult to get right across all versions. I'd recommend upgrading to Xcode 14 as soon as possible and this error will likely go away. There is a related discussion in https://github.com/bugfender/BugfenderSDK-iOS/issues/81

**Comment by mmaass** [comment]
Thanks for the feedback. I was able to create the archive by disabling Bitcode entirely.
