### ISSUE TITLE
Can't log objects???

### ISSUE THREAD

**Issue by marcolino** [bugfender/rn-bugfender#7]
Logging an object with rn-bugfender I get:

    com.facebook.bridge.ReadableNativeMap cannot be cast to java.lang.String

I kno I can JSON.stringify my object before logging, but, what a shame... :-(

**Comment by jgimenez** [comment]
Hi @marcolino , this is an open source project, please feel free to contribute

**Comment by marcolino** [comment]
I will do it as soon I have some spare time... Thanks.
For the moment I added a hach on client code... :-(
