### ISSUE TITLE
Force method name

### ISSUE THREAD

**Issue by marcolino** [bugfender/rn-bugfender#8]
Logging with react-native, logged method name is always `java.lang.reflect.Method.invoke`, not  really useful. Is it possible to override calling method, passing the real js calling method?
Something like `arguments.callee.toString().substr('function '.length);`

**Comment by franmontiel** [comment]
Hi @marcolino, my apologies for the late response. You can use the log method that allows you to pass the method as an argument. 
You can check it in here: https://github.com/bugfender/rn-bugfender/blob/master/bugfender.js#L140
