### ISSUE TITLE
 Unable to resolve module @bugfender/common from @bugfender/rn-bugfender/src/index.tsx: @bugfender/common could not be found

### ISSUE THREAD

**Issue by PunainenAurinko** [bugfender/rn-bugfender#80]
I have the following error on @bugfender/rn-bugfender version 2.2.1 on both iOS and Android. 

I cleaned the project and reinstalled modules and pods multiple times, but I'm still getting this error. Any help will be appreciated.

<img width="1079" alt="Screenshot 2023-08-14 at 5 27 11 PM" src="https://github.com/bugfender/rn-bugfender/assets/8648354/d7dfc150-b166-46ff-858b-1bb28110bcda">

![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-14 at 17 36 19](https://github.com/bugfender/rn-bugfender/assets/8648354/d565aceb-4e79-46d2-a768-63e6067fa767)

**Comment by jgimenez** [comment]
Did you install @bugfender/common?

You'll need to install this module like this (see README for more details):

```
npm install @bugfender/rn-bugfender @bugfender/sdk @bugfender/common
```

**Comment by PunainenAurinko** [comment]
@jgimenez Thank you, my mistake. This is working with the addition of the other two packages. I totally missed it from the readme file, as it was not required before and I didn't see anything mentioned about it in the release change logs.

**Comment by jgimenez** [comment]
Thanks for letting me know, we'll see if it's possible to make the error more explicit. I'm a bit surprised npm lets you install a package without its dependencies?

**Comment by PunainenAurinko** [comment]
I'm using Yarn, maybe that's why?

**Comment by jgimenez** [comment]
Ah, maybe. I'm not sure how it works with Yarn. I confirmed npm will automatically install peer dependencies even if you don't ask it to.
