### ISSUE TITLE
self is not defined NextJS app

### ISSUE THREAD

**Issue by juanjlunar** [bugfender/rn-bugfender#82]
Hi there, this error happens when we try to init the library on a NextJS app using React Native Web on the _app.tsx entry point.

We tried transpiling the modules using the next.config.js but it didn't work either.

```
import { Bugfender } from '@bugfender/rn-bugfender';

Bugfender.init({
appKey: 'MY_APP_KEY'
})
```

Or

```
import { Bugfender } from '@bugfender/sdk';

Bugfender.init({
appKey: 'MY_APP_KEY'
})
```

Transpiling the packages in the next.config.js.

![Screenshot 2023-12-25 at 4 07 37 PM](https://github.com/bugfender/rn-bugfender/assets/26415034/ef2fd3ad-df04-4a10-81d0-cf741d63af92)

Without transpiling the '@bugfender/rn-bugfender' module.

![Screenshot 2023-12-25 at 4 30 01 PM](https://github.com/bugfender/rn-bugfender/assets/26415034/ce109766-93d6-4af3-a196-d544a7642d4f)

Using a react app using webpack it works fine, apparently, something is happening with the NextJS config.

**Comment by jgimenez** [comment]
Hi @juanjlunar, Bugfender is for front-end applications, so you can't run it on a Node.js server.

**Comment by juanjlunar** [comment]
I managed to make it work just fine using NextJS, but I think you should add the support for NextJS, this is a frontend app.

**Comment by jgimenez** [comment]
What kind of support is missing? How did you make it work?
